//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoServiceModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderID { get; set; }
        public System.DateTime WorksStart { get; set; }
        public Nullable<System.DateTime> WorksFinish { get; set; }
        public int WorksPrice { get; set; }
        public int CustomerID { get; set; }
        public int AutoID { get; set; }
        public int WorksID { get; set; }
    
        public virtual Automobiles Automobiles { get; set; }
        public virtual Customers Customers { get; set; }
        public virtual Works Works { get; set; }
    }
}
