//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoServiceModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorksAutoOrder
    {
        public int OrderID { get; set; }
        public string CarBrand { get; set; }
        public string CarModel { get; set; }
        public string TransmissionType { get; set; }
        public Nullable<int> EnginePower { get; set; }
        public Nullable<int> YearMade { get; set; }
        public string WorksName { get; set; }
        public System.DateTime WorksStart { get; set; }
        public Nullable<System.DateTime> WorksFinish { get; set; }
        public int WorksPrice { get; set; }
    }
}
